"""Generate LaTeX tables from frozen, copied CSV evidence; no model execution.

Run with the project's Python environment. All paths are relative to this
script, so the source archive is portable. pandas is the only dependency.
"""
from pathlib import Path
import hashlib
import json
import re
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'tables'
OUT.mkdir(exist_ok=True)
PROVENANCE = []

def read(name):
    path = ROOT / 'data' / (name + '.csv')
    PROVENANCE.append({'source': str(path.relative_to(ROOT)),
                       'sha256': hashlib.sha256(path.read_bytes()).hexdigest()})
    return pd.read_csv(path)

def esc(value):
    return str(value).replace('&', r'\&').replace('_', r'\_').replace('%', r'\%')

def model(value):
    if str(value) == 'dp_popularity': return 'DP popularity'
    value = str(value).replace('historical_B4', 'Hist. B4').replace('B4_main', 'B4')
    value = value.replace('B4_fixeddiag', 'B4 diag.').replace('fixed', 'FixedB')
    value = value.replace('full', 'Full').replace('two', 'Two').replace('pop', 'Pop')
    value = value.replace('_', ' ')
    value = re.sub(r'eps(\d+)', r'$\\epsilon=\1$', value)
    return esc(value)

def level(x):
    return {'nodp': 'No DP', 'clip': 'Clip only'}.get(str(x), str(x).replace('eps', ''))

def num(x, digits=6):
    return '---' if pd.isna(x) else f'{x:.{digits}f}'

def pm(m, sd, digits=5):
    if pd.isna(sd): return num(m, digits)
    return f'${m:.{digits}f}\\pm{sd:.{digits}f}$'

def sci(x):
    if pd.isna(x): return '---'
    if x == 0: return '$0$'
    a,b=f'{x:.3e}'.split('e')
    return f'${a}\\times10^{{{int(b)}}}$'

def table(name, caption, label, headers, rows, spec=None, note='', long=False):
    spec = spec or ('l' + 'r'*(len(headers)-1))
    if long:
        start = ('{\\small\n\\setlength{\\tabcolsep}{4pt}\n'
                 f'\\begin{{longtable}}{{{spec}}}\n\\caption{{{caption}}}\\label{{{label}}}\\\\\n'
                 '\\toprule\n' + ' & '.join(headers) + ' \\\\\n\\midrule\\endfirsthead\n'
                 f'\\multicolumn{{{len(headers)}}}{{l}}{{\\small\\itshape Table \\thetable\ (continued)}}\\\\\n'
                 '\\toprule\n' + ' & '.join(headers) + ' \\\\\n\\midrule\\endhead\n'
                 '\\midrule\n' + f'\\multicolumn{{{len(headers)}}}{{r}}{{\\footnotesize Continued on next page}}\\\\\n'
                 '\\endfoot\n\\bottomrule\\endlastfoot\n')
        end = '\\end{longtable}\n' + (f'\\tabnote{{{note}}}\n' if note else '') + '}\n'
    else:
        start = (f'\\begin{{table}}[tbp]\\centering\\small\n\\caption{{{caption}}}\\label{{{label}}}\n'
                 '\\setlength{\\tabcolsep}{4pt}\n' + f'\\begin{{tabular}}{{{spec}}}\\toprule\n'
                 + ' & '.join(headers) + ' \\\\\n\\midrule\n')
        end = '\\bottomrule\\end{tabular}\n' + (f'\\tabnote{{{note}}}\n' if note else '') + '\\end{table}\n'
    body = '\n'.join(' & '.join(map(str, r)) + r' \\' for r in rows) + '\n'
    (OUT/(name+'.tex')).write_text('% Generated by scripts/generate_tables.py; do not edit numeric cells.\n'+start+body+end)

b = read('baselines/final_5seed_means')
c = read('baselines/centralized_federated_3seeds')
sanity=[]
for name in ['random_reference','nonprivate_popularity']:
    d=read('baselines/'+name)
    for _,r in d.iterrows():
        sanity.append([esc(r.model),r['split'],num(r['ndcg@10']),num(r['ndcg@10_se']),num(r['hr@10']),num(r['mrr@10'])])
table('sanity_all','Phase-0 random and raw-popularity references.','tab:s-sanity',
      ['Model','Split','NDCG@10','User SE','HR@10','MRR@10'],sanity,long=True,
      note='SE describes across-user metric uncertainty for the retained reference, not training-seed SD. Random ranking uses seed 42; raw popularity is nonprivate. Both use the frozen full-ranking evaluator.')
w=read('baselines/weighting_paired')
table('weighting_all','Three-seed weighting and federation decomposition.','tab:s-weighting',
      ['Comparison','Mean difference','95\\% interval'],
      [[esc(r.comparison),num(r.mean_diff),f'[{num(r.ci_low)}, {num(r.ci_high)}]'] for _,r in w.iterrows()],
      long=True,note='These overall paired intervals all include zero. This family uses the matched three-seed control, not the later five-seed B1 mean.')
table('central_main', 'Matched centralized and federated controls (three seeds).', 'tab:central',
      ['Model', 'NDCG@10', 'Seed SD', 'HR@10', 'MRR@10'],
      [[r.model, num(r['test_ndcg@10']),num(r['test_ndcg@10_std']),num(r['test_hr@10']),num(r['test_mrr@10'])] for _,r in c.iterrows()],
      note='Seeds 42/123/2026. This B1 mean differs from the five-seed B1 mean used in later comparisons. Source: centralized\_federated\_3seeds.csv.')
p=read('baselines/privacy_accounting')
p=p[p['T']==50].sort_values('target_epsilon',ascending=False)
table('privacy_main','Final iterative privacy calibration at $q=0.1$, $T=50$, $\\delta=10^{-5}$.','tab:privacy',
      ['$\\epsilon$ target','$\\sigma$','PRV bound','RDP cross-check'],
      [[int(r.target_epsilon),num(r.noise_multiplier,9),num(r.epsilon),num(r.epsilon_cross_check)] for _,r in p.iterrows()],
      note='PRV is primary. RDP is a separate bound on the same mechanism. Source: privacy\_accounting.csv, final 50-round rows.')
bc=read('baselines/paired_contrasts')
z=bc[bc.family=='B3_vs_B1']
rows=[]
for _,r in b[b.family.isin(['B1','B3'])].iterrows():
    ci=z[z.a==r.model]
    v='Reference' if ci.empty else f'[{num(ci.iloc[0].sim_lo)}, {num(ci.iloc[0].sim_hi)}]'
    rows.append([model(r.model),pm(r.test_ndcg_mean,r.test_ndcg_seed_sd),v])
table('nonprivate_main','Converged nonprivate federated utility (five seeds).','tab:nonprivate',
      ['Model','NDCG@10 $\\pm$ seed SD','Adjusted interval vs. B1'],rows,
      note='Intervals are 98.75\\% paired-user bootstrap intervals for the four-comparison B3 family. Source: final\_5seed\_means.csv and paired\_contrasts.csv.')
rows=[]
for lv in ['nodp','eps8','eps4','eps2','eps1']:
    rr=[level(lv)]
    for m in ['B2_'+lv]+[f'B4_main_r{r}_{lv}' for r in [4,8,16,32]]:
        x=b[b.model==m].iloc[0];rr.append(num(x.test_ndcg_mean))
    rows.append(rr)
table('historical_main','Historical private and matched no-DP test NDCG@10 (five-seed means).','tab:historical',
      ['Target / control','B2 Full','B4 r4','B4 r8','B4 r16','B4 r32'],rows,
      note='All rows use 50 rounds. Historical tuning opportunities differ. Seed SDs and secondary metrics appear in the supplement. Source: final\_5seed\_means.csv.')
e=read('effective_noise/test_means')
ranks=read('effective_noise/rank_selection')
rows=[]
for lv in ['eps8','eps4','eps2','eps1']:
    rr=[level(lv)]
    for family in ['full','two','fixed','pop']:
        suffix=''
        if family in ['two','fixed']:
            rank=int(ranks[(ranks.method==family)&(ranks.level==lv)].iloc[0]['rank']);m=f'{family}_r{rank}_{lv}';suffix=f' (r{rank})'
        else:m=f'{family}_{lv}'
        x=e[e.model==m].iloc[0];rr.append(num(x.ndcg_mean)+suffix)
    rows.append(rr)
table('e1_main','E1 test utility with ranks selected on validation at each privacy level.','tab:e1',
      ['$\\epsilon$','Full','Two','FixedB','DP popularity'],rows,
      note='Five-seed NDCG@10 means. The primary E1 family compares matched ranks, not these separately selected ranks. Source: test\_means.csv and rank\_selection.csv.')
v=read('noise_replication/validation_summary')
table('e3_validation_main','Transferred MovieLens-1M validation NDCG@10.','tab:e3validation',
      ['Method','$\\epsilon=1$','$\\epsilon=2$'],
      [[model(u)]+[pm(v[(v.unit==u)&(v.level==lv)].iloc[0]['mean'],v[(v.unit==u)&(v.level==lv)].iloc[0]['std'],6) for lv in ['eps1','eps2']] for u in ['full','fixed_r8','two_r8','dp_popularity']],
      note='Mean and seed SD, five seeds. Settings transfer without retuning. No ML-1M test scoring. Source: validation\_summary.csv.')
ep=read('noise_replication/endpoint_summary')
rows=[]
for data in ['ml100k','ml1m']:
    for lv in ['eps1','eps2']:
        rr=[{'ml100k':'ML-100K','ml1m':'ML-1M'}[data],level(lv)]
        for bal,cp in [('svd','raw'),('svd','aligned'),('none','raw'),('none','aligned')]:
            x=ep[(ep.dataset==data)&(ep.level==lv)&(ep.unit=='two_r8')&(ep.balancing==bal)&(ep.coupling==cp)].iloc[0]
            rr.append(num(100*x.top10_churn_mean,4))
        rows.append(rr)
table('e3_churn_main','E3 shared-reset top-10 disagreement at lag ten (percent of set entries).','tab:e3churn',
      ['Dataset','$\\epsilon$','SVD/raw','SVD/aligned','None/raw','None/aligned'],rows,
      note='Two-r8; 128 observer users; two draws averaged within each of five seeds. None disables balancing only in the continuation. Source: endpoint\_summary.csv.')
comm=read('baselines/communication')
table('communication','Modeled dense tensor communication for retained historical methods.','tab:communication',
      ['Model','Bytes/client/round','Rounds to best','GB to best','GB complete'],
      [[model(r.model).replace(' all levels',''),f'{int(r.bytes_per_client_round):,}',num(r.rounds_to_best_mean,1),num(r.GB_to_best_mean,3),num(r.GB_all_rounds_mean,3)] for _,r in comm.iterrows()],
      long=True,note='Decimal GB; realized-participation totals averaged over seeds. Headers, secure aggregation, compression, and device costs excluded. Source: communication.csv.')
table('baseline_all','All retained five-seed historical utility rows.','tab:s-baselines',
      ['Model','NDCG@10','HR@10','MRR@10'],
      [[model(r.model),pm(r.test_ndcg_mean,r.test_ndcg_seed_sd),pm(r.test_hr_mean,r.test_hr_seed_sd),pm(r.test_mrr_mean,r.test_mrr_seed_sd)] for _,r in b.iterrows()],
      long=True,note='Entries are mean $\\pm$ seed SD. B4 diag. denotes the historical fixed-setting diagnostic, not E1-FixedB.')
table('e1_all','All retained E1 utility rows.','tab:s-e1',
      ['Model','Seeds','NDCG@10','HR@10','MRR@10'],
      [[model(r.model),int(r.n_seeds),pm(r.ndcg_mean,r.ndcg_seed_sd),pm(r.hr_mean,r.hr_seed_sd),pm(r.mrr_mean,r.mrr_seed_sd)] for _,r in e.iterrows()],
      long=True,note='Entries are mean $\\pm$ seed SD. The bounded no-noise popularity reference is deterministic; its SD is not training variability.')
ec=read('effective_noise/contrasts')
def contrasts(df,name,label,title):
    rows=[]
    for family,g in df.groupby('family',sort=False):
        rows.append([f'\\multicolumn{{5}}{{l}}{{\\textit{{{esc(family)}}}}}'])
        for _,r in g.iterrows():
            adj='---' if pd.isna(r.sim_lo) else f'[{num(r.sim_lo)}, {num(r.sim_hi)}]'
            decision='Secondary'
            if not pd.isna(r.sim_lo):decision='Positive' if r.sim_lo>0 else ('Negative' if r.sim_hi<0 else 'Includes zero')
            rows.append([model(r.a)+' $-$ '+model(r.b),num(r['diff']),f'[{num(r.ci95_lo)}, {num(r.ci95_hi)}]',adj,decision])
    table(name,title,label,['Contrast ($a-b$)','Difference','95\\% interval','Adjusted interval','Decision'],rows,
          spec='L{.27\\linewidth}L{.10\\linewidth}L{.22\\linewidth}L{.22\\linewidth}L{.10\\linewidth}',long=True,
          note='Decisions refer only to declared adjusted families; secondary 95\\% intervals have no family-wide claim. User metrics are averaged over five seeds before resampling.')
contrasts(bc,'baseline_contrasts','tab:s-baselinecontrasts','Historical paired-user contrasts, including secondary families.')
contrasts(ec,'e1_contrasts','tab:s-e1contrasts','E1 paired-user contrasts, including secondary families.')
geo=read('effective_noise/geometry_means')
rows=[]
for _,r in geo.iterrows():
    rows.append([model(r.unit),level(r.level),num(r.q_noise_norm_rms,4),sci(r.score_noise_rmse_mean),num(100*r.expected_cross_fraction,4),num(100*r.frac_clipped_mean,2),sci(r.final_mean_user_norm)])
table('geometry_all','E1 effective-noise and clipping diagnostics across all 54 settings.','tab:s-geometry',
      ['Unit','Level','$Q$ noise norm','Score RMSE','Cross (\\%)','Clipped (\\%)','Mean $\\|p\\|$'],rows,long=True,
      note='Q noise norm is the mean over seeds of per-run root-mean-squared Frobenius norms, not entrywise RMS. Cross is the expected bilinear fraction of matrix-noise energy. Score RMSE can be dominated by large finite local vectors.')
sub=read('effective_noise/subgroups_test')
rows=[]
for m,g in sub.groupby('model',sort=False):
    rr=[model(m)]
    for group in ['low_activity','medium_activity','high_activity','cold_target','warm_target']:
        x=g[g.group==group];rr.append('---' if x.empty else num(x.iloc[0].ndcg_mean,5))
    rows.append(rr)
table('subgroups_all','Descriptive activity and cold-target NDCG@10, including historical comparators.','tab:s-subgroups',
      ['Model','Low (319)','Medium (310)','High (313)','Cold (14)','Warm (928)'],rows,long=True,
      note='No subgroup significance claim. Group sizes are users/test targets. Historical B4 rows are retained comparator rows; all model identities remain explicit.')
pers=read('effective_noise/personalization_validation')
z=pers.groupby(['unit','level','mode']).ndcg.agg(['mean','std'])
rows=[]
for unit,lv in pers[['unit','level']].drop_duplicates().itertuples(index=False,name=None):
    rr=[model(unit),level(lv)]
    for mode in ['own','permuted','mean']:
        x=z.loc[(unit,lv,mode)];rr.append(pm(x['mean'],x['std']))
    rows.append(rr)
table('personalization_all','E1 validation personalization ablations (five-seed mean and SD).','tab:s-personalization',
      ['Unit','Level','Own user vector','Permuted vector','Mean vector'],rows,long=True,
      note='810 original rows aggregate into 54 unit/level settings. These diagnostic alternatives are not privacy-accounted serving mechanisms.')
rows=[]
for folder,name in [('noise_memory','E2 raw'),('noise_memory_aligned','E2b aligned')]:
    x=read(folder+'/summary')
    # Preserve all declared amplitudes and branches at the final diagnostic lag.
    x=x[(x.phase=='after_reset')&(x.lag==10)]
    for _,r in x.iterrows():
        rows.append([name+' '+model(r.unit),level(r.level),num(r.alpha,2),esc(r.branch),
                     num(100*r.top10_churn_all_mean,4),sci(r.score_difference_rms_mean),num(r.score_ratio_to_pulse_mean,4)])
table('memory_endpoints','E2/E2b lag-ten diagnostics across both pulse amplitudes and all reset branches.','tab:s-memory',
      ['Study/unit','Level','$\\alpha$','Branch','Churn (\\%)','Score RMS','RMS/pulse'],rows,
      spec='llrlrrr',long=True,note='Each entry averages two draws within seed, then five seeds. A mean ratio can be dominated by a small denominator or an unstable seed; original medians and seed tables remain available.')
rows=[]
for _,r in ep.iterrows():
    rows.append([r.dataset,model(r.unit),level(r.level),r.balancing+'/'+r.coupling,pm(100*r.top10_churn_mean,100*r.top10_churn_std,4),sci(r.score_rms_mean),num(r.validation_ndcg_difference_mean,6)])
table('replication_endpoints','All E3 shared-reset lag-ten settings.','tab:s-e3',
      ['Data','Unit','Level','Balance/coupling','Churn (\\%)','Score RMS','$\\Delta$ val. NDCG'],rows,long=True,
      note='Churn includes seed SD; other columns show seed means. Validation differences use only 128 observer users and have limited resolution. Starting checkpoint epsilon does not account for continuation.')
tail=read('ranking_tails/screen_summary')
table('tail_screen','Complete E4 state-group screening summary.','tab:s-tail',
      ['Data','Unit','Level','Matched max error','Linear max error','Mean cross (\\%)'],
      [[r.dataset,model(r.unit),level(r.level),sci(r.absolute_error_matched_max),sci(r.absolute_error_linear_max),num(100*r.bilinear_share_mean,5)] for _,r in tail.iterrows()],
      long=True,note='Each row summarizes 320 prescribed records. Cross is pairwise margin-variance share, not E1 whole-matrix energy. Maximum error is an absolute probability difference.')
ac=read('effective_noise/accounting')
mc=read('effective_noise/synthetic_monte_carlo')
table('moments_all','E1 synthetic checks of conditional moment calculations.','tab:s-moments',
      ['Method','$\\tau$','Draws','$Q$: measured/expected','Scores: measured/expected'],
      [[model(r.method),num(r.tau,3),int(r.draws),num(r.q_ratio),num(r.score_ratio)] for _,r in mc.iterrows()],
      long=True,note='Eight synthetic cases, 2,000 draws each. Finite Monte Carlo discrepancies are expected; these are implementation checks rather than real-data utility results.')
table('accounting_all','Calibration of the iterative and one-release mechanisms.','tab:s-accounting',
      ['Mechanism','$\\epsilon$ target','$\\sigma$','Achieved $\\epsilon$','$q$','$T$'],
      [[esc(r.mechanism),int(r.target_epsilon),num(r.sigma,9),num(r.epsilon),num(r.q,1),int(r['T'])] for _,r in ac.iterrows()],
      long=True,note='Delta is $10^{-5}$ throughout. Popularity is a full-population single Gaussian release; its multiplier is not interchangeable with collaborative calibration.')
table('rank_selection','Validation-only rank selections for E1.','tab:s-ranks',
      ['Method','Level','Selected rank','Validation NDCG@10'],
      [[model(r.method),level(r.level),int(r['rank']),num(r.val_ndcg_mean)] for _,r in ranks.iterrows()],long=True)
# Record exact identities and counts, not a claim of a newly trained experiment.
unique={x['source']:x for x in PROVENANCE}
manifest={'inputs':list(unique.values()),'generated_tables':len(list(OUT.glob('*.tex'))),
          'baseline_utility_rows':len(b),'e1_utility_rows':len(e),
          'historical_contrasts':len(bc),'e1_contrasts':len(ec),
          'activity_rows':len(sub),'personalization_rows':len(pers),
          'training_executed':False,'additional_test_scoring':False}
(ROOT/'quality'/'table_provenance.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps({k:v for k,v in manifest.items() if k!='inputs'},indent=2))
